/**
 * CHECK-DB-COLUMNS — `packages/db/src/types.ts` against the real schema
 *
 * `packages/db/src/types.ts` is hand-written. Its own header says so, and says
 * it must change in the same commit as the migration — which is exactly the
 * kind of promise that holds until the day it doesn't. A column added to a
 * migration and forgotten here does not fail the build; it fails at runtime, as
 * a field that is silently `undefined` in a query result. This closes that gap.
 *
 * For every table in `public`, the column names Postgres reports are compared
 * to the field names in that table's `Row` type. Nullability and Postgres types
 * are NOT compared — mapping `numeric` or `text[]` onto a TS type involves
 * judgement calls the file documents and this script has no business second-
 * guessing. Presence is the thing that actually breaks silently.
 *
 * Needs a live database, so it runs in the `migrations` CI job (which already
 * has one) rather than in `npm run check`. Connection comes from the standard
 * PG* environment variables, via psql — no driver dependency.
 *
 * Usage:  npx tsx scripts/check-db-columns.ts
 */

import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { PATHS } from './lib/paths.js';

const TYPES = path.join(PATHS.root, 'packages', 'db', 'src', 'types.ts');

interface Column {
  table: string;
  column: string;
}

function fromPostgres(): Column[] {
  const sql = `
    select c.table_name || E'\\t' || c.column_name
      from information_schema.columns c
      join information_schema.tables t
        on t.table_schema = c.table_schema and t.table_name = c.table_name
     where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
     order by c.table_name, c.ordinal_position`;

  let out: string;
  try {
    out = execFileSync('psql', ['-tA', '-v', 'ON_ERROR_STOP=1', '-c', sql], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    process.stderr.write(
      `could not reach Postgres through psql — this check needs a live database.\n${msg}\n`,
    );
    process.exit(2);
  }

  return out
    .split('\n')
    .filter((l) => l.includes('\t'))
    .map((l) => {
      const [table, column] = l.split('\t');
      return { table: table!, column: column! };
    });
}

/**
 * Pull the `Row` field names out of each table block.
 *
 * A real TypeScript parse would be more principled, but the file is generated
 * in a rigid shape (`supabase gen types` emits it, and the hand-written stand-in
 * copies that shape exactly), so a structural read of it is stable — and it
 * stays stable the day the file is regenerated by the real generator, which is
 * the whole point of matching its layout.
 */
function fromTypes(): Map<string, Set<string>> {
  const src = readFileSync(TYPES, 'utf8');
  const tables = new Map<string, Set<string>>();

  const blocks = src.matchAll(
    /\n {6}(\w+): \{\n {8}Row: \{\n([\s\S]*?)\n {8}\}\n {8}Insert:/g,
  );
  for (const m of blocks) {
    const fields = new Set<string>();
    for (const line of m[2]!.split('\n')) {
      const f = /^\s{10}(\w+)\??:/.exec(line);
      if (f) fields.add(f[1]!);
    }
    tables.set(m[1]!, fields);
  }
  return tables;
}

function main(): void {
  const db = fromPostgres();
  const ts = fromTypes();

  if (ts.size === 0) {
    process.stderr.write(`parsed no tables out of ${TYPES} — the shape changed.\n`);
    process.exit(1);
  }

  const byTable = new Map<string, Set<string>>();
  for (const { table, column } of db) {
    if (!byTable.has(table)) byTable.set(table, new Set());
    byTable.get(table)!.add(column);
  }

  const problems: string[] = [];

  for (const [table, columns] of byTable) {
    const typed = ts.get(table);
    if (!typed) {
      problems.push(`  ${table} — in the database, absent from types.ts`);
      continue;
    }
    const missing = [...columns].filter((c) => !typed.has(c));
    const extra = [...typed].filter((c) => !columns.has(c));
    if (missing.length) problems.push(`  ${table}.Row is missing: ${missing.join(', ')}`);
    if (extra.length) problems.push(`  ${table}.Row has columns the database does not: ${extra.join(', ')}`);
  }

  for (const table of ts.keys()) {
    if (!byTable.has(table)) problems.push(`  ${table} — in types.ts, absent from the database`);
  }

  process.stdout.write('Longevity OS — db column parity\n\n');

  if (problems.length) {
    process.stdout.write(`  ${byTable.size} tables in Postgres · ${ts.size} in types.ts\n\n`);
    process.stderr.write(`packages/db/src/types.ts does not match the migrations:\n${problems.join('\n')}\n\n`);
    process.stderr.write(
      'Update it in the same commit as the migration — or, once the project is\n' +
        'linked, regenerate it:\n' +
        '  npx supabase gen types typescript --local > packages/db/src/types.ts\n',
    );
    process.exit(1);
  }

  const cols = [...byTable.values()].reduce((n, s) => n + s.size, 0);
  process.stdout.write(`  ✓ ${byTable.size} tables · ${cols} columns · types.ts agrees\n`);
}

main();
