/**
 * Longevity OS — curated exercise records
 *
 * Hand-authored `Exercise` records for movements the public datasets do not
 * cover: the Knees Over Toes catalogue, the McGill Big 3, the plyometric
 * ladder, the barbell-free "CrossFit at Planet Fitness" dumbbell movements, and
 * the cardio pseudo-exercises the engine prescribes as sessions.
 *
 * Because these have NO media (free-exercise-db has no images for them and the
 * Gym Visual set has no GIFs), every record carries a written `cue` and full
 * `instructions` — the text IS the media until Seth records his own clips.
 *
 * Run `npx tsx scripts/curated-exercises.ts` to emit `data/curated-exercises.json`.
 * `scripts/ingest-exercises.ts` imports CURATED_EXERCISES directly to compute
 * KOT media gaps.
 */

import type { Exercise } from '../packages/engine/src/types';
import { PATHS, writeJson } from './lib/paths';

/** Attribution-free: these are our own words, written for this app. */
const CURATED: Exercise[] = [
  // ───────────────────────────────────────────────────────────────────────────
  // KOT — backward locomotion
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'backward-sled-drag',
    name: 'Backward Sled Drag',
    slug: 'backward-sled-drag',
    aliases: ['sled drag backward', 'reverse sled drag', 'backwards sled'],
    pattern: 'gait',
    force: 'pull',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['sled'],
    region_loads: { knees_quads: 0.8, calves_achilles: 0.4, hips_glutes: 0.3, core: 0.2 },
    load_style: 'single_implement',
    barbell_free: false,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'backward_locomotion',
    cue: 'Small quick steps, stay tall, let the knee travel forward over the toe under control.',
    instructions: [
      'Load the sled to roughly 50% of bodyweight to start; it should be draggable for several unbroken minutes.',
      'Face the sled, hold the straps or handles at hip height, arms long.',
      'Walk backwards with short quick steps, planting through the ball of the foot then the heel.',
      'Keep the torso tall — no leaning back and hanging off the straps.',
      'Work for time (5–10 minutes) rather than for reps. Knees should feel better afterwards, not worse.',
    ],
    preferred_alternatives: ['backward-treadmill-walk', 'backward-walk-outdoors'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },
  {
    id: 'backward-treadmill-walk',
    name: 'Backward Treadmill Walk (Powered Off)',
    slug: 'backward-treadmill-walk',
    aliases: ['deadmill backward walk', 'backward walking treadmill', 'reverse treadmill walk'],
    pattern: 'gait',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['treadmill'],
    region_loads: { knees_quads: 0.7, calves_achilles: 0.4, hips_glutes: 0.3 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'backward_locomotion',
    cue: 'Belt OFF. You are the motor — push the belt behind you, toe first.',
    instructions: [
      'Leave the treadmill powered off. Straddle or stand on the belt and hold the rails lightly.',
      'Face the console, step backwards, driving the belt with the ball of the foot then rolling to the heel.',
      'Hold the rails only as much as you need for balance; aim to let go over time.',
      'Accumulate 5–10 minutes. This is the Planet Fitness substitute for the backward sled.',
      'Stop if the knee pain rises 2 points or more; reduce to flat-ground backward walking.',
    ],
    preferred_alternatives: ['backward-walk-outdoors', 'backward-sled-drag'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },
  {
    id: 'backward-walk-outdoors',
    name: 'Backward Walking (Outdoors)',
    slug: 'backward-walk-outdoors',
    aliases: ['reverse walking', 'rokp', 'reverse out knee pain walk', 'backwards walk'],
    pattern: 'gait',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['outdoor_route', 'track_or_open_space'],
    region_loads: { knees_quads: 0.6, calves_achilles: 0.3, hips_glutes: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'backward_locomotion',
    cue: 'Ten minutes, toe down first, glance over one shoulder every few steps.',
    instructions: [
      'Pick a flat, clear, traffic-free stretch — a track, an empty lot, a long hallway.',
      'Walk backwards for 10 minutes, landing on the ball of the foot and rolling back to the heel.',
      'Keep steps short and quick rather than long and reaching.',
      'Look over alternating shoulders periodically rather than twisting the neck one way the whole time.',
      'This is the Zero-equipment entry point of the program: 3×/week minimum.',
    ],
    preferred_alternatives: ['backward-treadmill-walk', 'backward-sled-drag'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // KOT — lower legs
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'tibialis-raise',
    name: 'Tibialis Raise (Bodyweight)',
    slug: 'tibialis-raise',
    aliases: ['tib raise', 'wall tibialis raise', 'toe raise against wall'],
    pattern: 'isolation_lower',
    force: 'pull',
    mechanic: 'isolation',
    level: 'beginner',
    equipment: ['bodyweight', 'wall_space'],
    region_loads: { calves_achilles: 0.9, knees_quads: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'lower_legs',
    cue: 'Heels planted, lean back on the wall, pull the toes up hard and lower slowly.',
    instructions: [
      'Stand with your back against a wall, heels 6–12 inches out from the wall (further out = harder).',
      'Keep legs straight and the back and hips in contact with the wall.',
      'Pull the toes and forefoot up toward the shins as high as they will go.',
      'Lower under control — do not let the feet slap down.',
      'The standard is 25 unbroken reps. Build there before adding load.',
    ],
    preferred_alternatives: ['tibialis-raise-band', 'tibialis-raise-dumbbell', 'tib-bar-raise'],
    rehab_for: ['knees_quads', 'calves_achilles'],
    source: 'curated',
  },
  {
    id: 'tibialis-raise-band',
    name: 'Tibialis Raise (Band)',
    slug: 'tibialis-raise-band',
    aliases: ['banded tib raise', 'band dorsiflexion'],
    pattern: 'isolation_lower',
    force: 'pull',
    mechanic: 'isolation',
    level: 'beginner',
    equipment: ['resistance_bands'],
    region_loads: { calves_achilles: 0.9 },
    load_style: 'band',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'lower_legs',
    cue: 'Anchor low and in front; pull the toes back against the band, pause at the top.',
    instructions: [
      'Sit on the floor or a bench with legs extended and the band anchored low in front of you.',
      'Loop the band over the forefoot, heel resting on the ground.',
      'Pull the toes back toward the shin against the band; pause one second at the top.',
      'Lower slowly over 2–3 seconds.',
      'Use when no tib bar is available and bodyweight raises have become easy.',
    ],
    preferred_alternatives: ['tibialis-raise-dumbbell', 'tib-bar-raise', 'tibialis-raise'],
    rehab_for: ['calves_achilles'],
    source: 'curated',
  },
  {
    id: 'tibialis-raise-dumbbell',
    name: 'Tibialis Raise (Dumbbell Between the Feet)',
    slug: 'tibialis-raise-dumbbell',
    aliases: ['db tib raise', 'weighted tibialis raise', 'dumbbell dorsiflexion'],
    pattern: 'isolation_lower',
    force: 'pull',
    mechanic: 'isolation',
    level: 'intermediate',
    equipment: ['dumbbell', 'bench_flat'],
    region_loads: { calves_achilles: 1, knees_quads: 0.2 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'lower_legs',
    cue: 'Pinch the dumbbell between the feet, heels on the edge, curl the toes up.',
    instructions: [
      'Sit on a bench with the heels resting on a block or the floor and the knees bent ~90°.',
      'Stand a dumbbell on end and pinch it between the forefeet, or hang it over the toes.',
      'Pull the toes up toward the shins through full range; pause at the top.',
      'Lower over 3 seconds. Keep the heels planted throughout.',
      'The tib bar standard is 25% bodyweight for 5×5; this is the Planet Fitness/home substitute.',
    ],
    preferred_alternatives: ['tib-bar-raise', 'tibialis-raise-band', 'tibialis-raise'],
    rehab_for: ['calves_achilles'],
    source: 'curated',
  },
  {
    id: 'tib-bar-raise',
    name: 'Tib Bar Raise',
    slug: 'tib-bar-raise',
    aliases: ['tibialis bar curl', 'tib bar curl', 'loaded tibialis raise'],
    pattern: 'isolation_lower',
    force: 'pull',
    mechanic: 'isolation',
    level: 'intermediate',
    equipment: ['tibialis_bar'],
    region_loads: { calves_achilles: 1, knees_quads: 0.2 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'lower_legs',
    cue: 'Heels fixed, toes drive the bar up — no rocking the knees.',
    instructions: [
      'Sit with the heels on a raised block and hook the tib bar over the forefeet.',
      'Keep the knees still; only the ankles move.',
      'Pull the toes up to full dorsiflexion, pause, and lower over 3 seconds.',
      'Standard: 25% of bodyweight for 5 sets of 5.',
      'If no tib bar is available, substitute the dumbbell-between-the-feet or band version.',
    ],
    preferred_alternatives: ['tibialis-raise-dumbbell', 'tibialis-raise-band', 'tibialis-raise'],
    rehab_for: ['calves_achilles'],
    source: 'curated',
  },
  {
    id: 'fhl-calf-raise',
    name: 'FHL Calf Raise',
    slug: 'fhl-calf-raise',
    aliases: ['flexor hallucis longus calf raise', 'big toe calf raise', 'fhl raise'],
    pattern: 'isolation_lower',
    force: 'push',
    mechanic: 'isolation',
    level: 'beginner',
    equipment: ['bodyweight', 'wall_space'],
    region_loads: { calves_achilles: 1 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'lower_legs',
    cue: 'Rise onto the big toe, not the pinky side — press the big toe into the floor.',
    instructions: [
      'Stand tall, fingertips on a wall for balance only.',
      'Rise onto the balls of the feet, deliberately pressing through the BIG toe so the ankle does not roll outward.',
      'Pause at the top for one second with the big toe loaded.',
      'Lower slowly to a full stretch at the bottom.',
      'This protects the Achilles and the plantar fascia and is the precursor to single-leg calf raise standards.',
    ],
    preferred_alternatives: ['single-leg-calf-raise'],
    rehab_for: ['calves_achilles'],
    source: 'curated',
  },
  {
    id: 'kot-seated-calf-raise',
    name: 'KOT Calf Raise (Seated, Bent Knee)',
    slug: 'kot-seated-calf-raise',
    aliases: ['seated calf raise (bodyweight)', 'bent-knee calf raise', 'soleus raise'],
    pattern: 'isolation_lower',
    force: 'push',
    mechanic: 'isolation',
    level: 'beginner',
    // A chair. That is the whole equipment list, which is the point: the
    // free-exercise-db record of the same name is a PIN-LOADED LEVER MACHINE
    // needing `selectorized_machine`, so pointing the step at it made the
    // movement unreachable in a bedroom and it was dropped from every Zero
    // session at home with a note nobody could act on.
    equipment: ['bodyweight', 'bench_flat'],
    region_loads: { calves_achilles: 1 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'lower_legs',
    cue: 'Knees bent, heels up — this one is the soleus, so the standing version does not replace it.',
    instructions: [
      'Sit on a chair or bench with the feet flat and the knees bent to about 90°.',
      'Drive through the balls of the feet and raise the heels as high as they will go.',
      'Pause at the top, then lower until the heels are back on the floor and the calf is at full stretch.',
      'Bending the knee takes the gastrocnemius out of it and leaves the soleus — the muscle that has to hold you on a landing, and the one a standing calf raise misses.',
      'Add load by resting a dumbbell across the knees once bodyweight is easy.',
    ],
    preferred_alternatives: ['fhl-calf-raise', 'single-leg-calf-raise'],
    rehab_for: ['calves_achilles'],
    source: 'curated',
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    slug: 'single-leg-calf-raise',
    aliases: ['one leg calf raise', 'unilateral calf raise', 'single leg heel raise'],
    pattern: 'isolation_lower',
    force: 'push',
    mechanic: 'isolation',
    level: 'intermediate',
    equipment: ['bodyweight', 'dumbbell', 'slant_board'],
    region_loads: { calves_achilles: 1, hips_glutes: 0.1 },
    load_style: 'total_dumbbell_pair',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'lower_legs',
    cue: 'Full stretch at the bottom, full squeeze at the top, no bouncing.',
    instructions: [
      'Stand on one foot with the forefoot on a step or a slant board, the heel free to drop.',
      'Drop the heel to a full stretch under control.',
      'Rise to the top of the range, pressing through the big toe, and pause.',
      'Standard: 25% of bodyweight held in one hand for 10 reps per leg.',
      'Balance with fingertips on a wall — do not pull yourself up with the hand.',
    ],
    preferred_alternatives: ['fhl-calf-raise'],
    rehab_for: ['calves_achilles'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // KOT — step-ups
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'patrick-step',
    name: 'Patrick Step',
    slug: 'patrick-step',
    aliases: ['patrick step down', 'reverse step down', 'knee over toe step'],
    pattern: 'lunge',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['bodyweight', 'plyo_box'],
    region_loads: { knees_quads: 0.9, hips_glutes: 0.3, calves_achilles: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: true,
    plyo_contacts_per_rep: 0,
    kot_step: 'step_ups',
    cue: 'Working knee travels forward, free leg straight, tap the heel — do not sit back.',
    instructions: [
      'Stand on a low step (2–4 inches to start) on one leg, the other leg straight out in front.',
      'Keeping the front leg locked straight, bend the standing knee and let it travel forward over the toes.',
      'Lower until the free heel taps the floor in front of the step.',
      'Press back up through the whole foot without rocking backwards.',
      'Full range with control before adding height. This is the strict-knee-over-toe step-down.',
    ],
    preferred_alternatives: ['poliquin-step', 'atg-split-squat-assisted'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },
  {
    id: 'poliquin-step',
    name: 'Poliquin Step-Up',
    slug: 'poliquin-step',
    aliases: ['poliquin step up', 'vmo step up', 'heel elevated step up'],
    pattern: 'lunge',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['plyo_box', 'dumbbell', 'slant_board'],
    region_loads: { knees_quads: 1, hips_glutes: 0.3, calves_achilles: 0.2 },
    load_style: 'total_dumbbell_pair',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'step_ups',
    cue: 'Heel elevated, knee forward over the toe, drive up through the working leg only.',
    instructions: [
      'Set a 3–4 inch box or plate. Stand with the working foot on the box, heel elevated on a small wedge if available.',
      'Let the knee travel forward over the toes as the free leg hangs behind.',
      'Drive up through the working leg without pushing off the back foot.',
      'Lower slowly under control; keep the torso upright.',
      'Standard: 66% of bodyweight (total load) for 20 reps on a 3–4 inch box.',
    ],
    preferred_alternatives: ['patrick-step', 'atg-split-squat'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // KOT — split squat
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'atg-split-squat-assisted',
    name: 'ATG Split Squat (Assisted)',
    slug: 'atg-split-squat-assisted',
    aliases: ['assisted atg split squat', 'supported atg split squat', 'elevated atg split squat'],
    pattern: 'lunge',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['bodyweight', 'resistance_bands', 'wall_space'],
    region_loads: { knees_quads: 0.8, hips_glutes: 0.4, posterior_chain: 0.2 },
    load_style: 'assisted',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'split_squat',
    cue: 'Hold the rail, front knee past the toes, back knee down to a full stretch.',
    instructions: [
      'Set up in a long split stance with the rear foot flat and the rear knee heading toward the floor.',
      'Hold a rail, doorframe, or band anchored in front at chest height, and use the arms to unload the legs.',
      'Descend until the hamstring covers the calf on the front leg and the rear hip is in a full stretch.',
      'Use as little arm assistance as you can manage; the goal is to reduce it session over session.',
      'Front foot may be elevated on a plate to reduce depth demand while ankle mobility improves.',
    ],
    preferred_alternatives: ['atg-split-squat', 'patrick-step'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },
  {
    id: 'atg-split-squat',
    name: 'ATG Split Squat',
    slug: 'atg-split-squat',
    aliases: ['atg split squat flat', 'knees over toes split squat', 'full range split squat'],
    pattern: 'lunge',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['bodyweight', 'dumbbell'],
    region_loads: { knees_quads: 1, hips_glutes: 0.5, posterior_chain: 0.3, calves_achilles: 0.2 },
    load_style: 'total_dumbbell_pair',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'split_squat',
    cue: 'Hamstring covers the calf at the bottom; knee tracks straight over the middle toes.',
    instructions: [
      'Stand in a long split stance, torso upright, rear leg straight behind you.',
      'Descend until the front hamstring covers the calf — full range, knee travelling forward over the toes.',
      'Keep the front heel planted; the rear knee lightly touches or hovers over the floor.',
      'Drive back up through the front foot without collapsing the knee inward.',
      'Standard: 25% of bodyweight PER HAND (dumbbells) through full range.',
    ],
    preferred_alternatives: ['atg-split-squat-assisted', 'poliquin-step'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },
  {
    id: 'elephant-walk',
    name: 'Elephant Walk',
    slug: 'elephant-walk',
    aliases: ['elephant walks', 'straight leg walk stretch'],
    pattern: 'mobility',
    force: 'static',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['bodyweight'],
    region_loads: { posterior_chain: 0.5, low_back: 0.2, calves_achilles: 0.3 },
    load_style: 'none',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'split_squat',
    cue: 'Hands on the floor, alternate pressing each heel down with the knee locked.',
    instructions: [
      'Hinge forward and place both hands on the floor (or on a block if the hamstrings are tight).',
      'Bend one knee while pressing the opposite heel toward the floor with that leg locked straight.',
      'Alternate slowly, "walking" in place, feeling the stretch move from calf to hamstring.',
      'Accumulate 20–30 alternating reps.',
      'Work toward hands flat on the floor with both knees locked.',
    ],
    preferred_alternatives: ['jefferson-curl', 'atg-rdl'],
    rehab_for: ['posterior_chain'],
    source: 'curated',
  },
  {
    id: 'couch-stretch',
    name: 'Couch Stretch',
    slug: 'couch-stretch',
    aliases: ['quad hip flexor wall stretch', 'kneeling quad stretch'],
    pattern: 'mobility',
    force: 'static',
    mechanic: 'isolation',
    level: 'beginner',
    equipment: ['wall_space', 'yoga_mat'],
    region_loads: { knees_quads: 0.3, hips_glutes: 0.4 },
    load_style: 'none',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'split_squat',
    cue: 'Rear shin up the wall, squeeze the glute, tuck the pelvis — then sit tall.',
    instructions: [
      'Kneel with the rear shin up against a wall and the rear knee in the corner where the wall meets the floor.',
      'Place the other foot flat in front in a lunge position.',
      'Squeeze the rear glute and tuck the pelvis under to remove the arch from the low back.',
      'Raise the torso toward vertical only as far as the pelvic tuck holds.',
      'Hold 60–90 seconds per side, breathing slowly. Pad the knee.',
    ],
    preferred_alternatives: ['reverse-nordic'],
    rehab_for: ['knees_quads', 'hips_glutes'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // KOT — deep squat
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'deep-squat-hold',
    name: 'Deep Squat Hold',
    slug: 'deep-squat-hold',
    aliases: ['third world squat', 'atg squat hold', 'bodyweight deep squat hold'],
    pattern: 'squat',
    force: 'static',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['bodyweight', 'slant_board'],
    region_loads: { knees_quads: 0.6, hips_glutes: 0.5, calves_achilles: 0.3, low_back: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'deep_squat',
    cue: 'Heels down, chest up, sit all the way in and breathe.',
    instructions: [
      'Stand with feet roughly shoulder width, toes slightly out.',
      'Squat all the way down until the hamstrings rest on the calves.',
      'Keep the heels flat; elevate them on a wedge or plates if they lift.',
      'Hold, breathing slowly, and gently pry the knees out with the elbows.',
      'Accumulate 3–5 minutes across the session. Progress toward heels flat and torso vertical.',
    ],
    preferred_alternatives: ['atg-split-squat', 'elephant-walk'],
    rehab_for: ['knees_quads', 'hips_glutes'],
    source: 'curated',
  },
  {
    id: 'atg-squat',
    name: 'ATG Squat',
    slug: 'atg-squat',
    aliases: ['full depth squat', 'knees over toes squat', 'goblet atg squat', 'heel elevated deep squat'],
    pattern: 'squat',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['dumbbell', 'kettlebell', 'slant_board', 'bodyweight'],
    region_loads: { knees_quads: 1, hips_glutes: 0.7, calves_achilles: 0.3, low_back: 0.3, core: 0.3 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'deep_squat',
    cue: 'All the way down, chest up, knees forward over the toes — no bouncing out of the hole.',
    instructions: [
      'Hold a dumbbell or kettlebell at the chest (goblet position), feet shoulder width.',
      'Squat to full depth — hamstrings on calves — with the heels down and the torso as upright as you can hold.',
      'Elevate the heels on a wedge or plates while ankle mobility is still building.',
      'Stand up smoothly without letting the knees cave in.',
      'Standard: 25% of bodyweight for 20 reps at full depth.',
    ],
    preferred_alternatives: ['deep-squat-hold', 'atg-split-squat'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },
  {
    id: 'l-sit',
    name: 'L-Sit',
    slug: 'l-sit',
    aliases: ['l sit hold', 'floor l-sit', 'parallette l-sit'],
    pattern: 'anti_extension',
    force: 'static',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['bodyweight', 'dip_station'],
    region_loads: { core: 1, hips_glutes: 0.4, elbows_forearms: 0.3, shoulders: 0.3 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'deep_squat',
    cue: 'Push the floor away, lock the knees, lift the toes above the hips if you can.',
    instructions: [
      'Sit on the floor with legs straight and hands flat beside the hips (or on parallettes/low blocks).',
      'Press down hard through the hands, depress the shoulders, and lift the hips off the floor.',
      'Keep the knees locked and lift the heels clear of the ground.',
      'Hold for time; start with tucked knees and progress to straight legs.',
      'Target 3 × 20–30 seconds.',
    ],
    preferred_alternatives: ['mcgill-curl-up', 'side-plank'],
    rehab_for: ['core'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // KOT — posterior chain / upper body accessory
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    slug: 'nordic-hamstring-curl',
    aliases: ['nordic curl', 'russian leg curl', 'natural glute ham raise', 'nordics'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'compound',
    level: 'expert',
    equipment: ['nordic_support', 'bench_adjustable', 'yoga_mat'],
    region_loads: { posterior_chain: 1, low_back: 0.3, hips_glutes: 0.4, core: 0.3 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: true,
    plyo_contacts_per_rep: 0,
    kot_step: 'posterior_chain',
    cue: 'Hips locked straight, lower as slowly as you can, catch with the hands.',
    instructions: [
      'Kneel with the ankles anchored under a Nordic strap, a loaded bench, or a partner. Pad the knees.',
      'Keep a straight line from knee to shoulder — do not hinge at the hip.',
      'Lower the torso toward the floor as slowly as you can control.',
      'Catch yourself with the hands and push back to the start, or pull with the hamstrings if strong enough.',
      'Standard: full bodyweight for 10 reps. ~50% reduction in hamstring injury risk (van Dyk 2019) — 1–2×/week.',
    ],
    preferred_alternatives: ['reverse-nordic', 'atg-rdl'],
    contraindicated_with: ['depth-jump'],
    rehab_for: ['posterior_chain'],
    source: 'curated',
  },
  {
    id: 'reverse-nordic',
    name: 'Reverse Nordic Curl',
    slug: 'reverse-nordic',
    aliases: ['reverse nordic curl', 'kneeling quad lean back', 'reverse nordics'],
    pattern: 'isolation_lower',
    force: 'pull',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['bodyweight', 'yoga_mat'],
    region_loads: { knees_quads: 1, hips_glutes: 0.3, core: 0.3 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: true,
    plyo_contacts_per_rep: 0,
    kot_step: 'posterior_chain',
    cue: 'Glutes squeezed, hips straight, lean back only as far as you can come back up.',
    instructions: [
      'Kneel tall on a pad with the feet plantarflexed (toes pointed).',
      'Squeeze the glutes and keep a straight line from knee to shoulder.',
      'Lean backwards slowly, bending only at the knees, feeling the quads stretch.',
      'Return by contracting the quads — no hip hinge, no arching the back.',
      'Build to 3 × 8–10 through the fullest range you can control.',
    ],
    preferred_alternatives: ['couch-stretch', 'nordic-hamstring-curl'],
    rehab_for: ['knees_quads'],
    source: 'curated',
  },
  {
    id: 'seated-good-morning',
    name: 'Seated Good Morning',
    slug: 'seated-good-morning',
    aliases: ['seated goodmorning', 'seated bent over good morning'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['bench_flat', 'dumbbell', 'smith_machine'],
    region_loads: { low_back: 0.9, posterior_chain: 0.6, spine: 0.5, core: 0.3 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'posterior_chain',
    cue: 'Seated, chest leads, arch held — hinge from the hips, not the low back.',
    instructions: [
      'Sit on the end of a bench, feet planted wide, load held across the upper back (Smith bar, DB, or a fixed bar).',
      'Hold a firm arch and lean the torso forward from the hips.',
      'Go as low as the arch holds — usually torso near parallel to the floor.',
      'Return by pulling the torso upright with the spinal erectors.',
      'Standard: 50% of bodyweight. Build slowly; this is a low-back strength builder, not a max lift.',
    ],
    preferred_alternatives: ['ql-extension', 'atg-rdl'],
    rehab_for: ['low_back'],
    source: 'curated',
  },
  {
    id: 'ql-extension',
    name: 'QL Extension',
    slug: 'ql-extension',
    aliases: ['quadratus lumborum extension', 'ql raise', 'back extension ql variation'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'isolation',
    level: 'intermediate',
    equipment: ['back_extension_bench', 'dumbbell'],
    region_loads: { low_back: 1, spine: 0.5, posterior_chain: 0.4, hips_glutes: 0.3 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'posterior_chain',
    cue: 'Round down segment by segment, then extend back up — slow, no swinging.',
    instructions: [
      'Set up on a 45° or horizontal back-extension bench with the pad below the hip crease.',
      'Hold a light dumbbell or plate at the chest.',
      'Lower by flexing the spine segment by segment under full control.',
      'Extend back up to a flat, neutral finish — do not hyperextend.',
      'Standard: 25% of bodyweight for 10 reps. Only once the back is pain-free.',
    ],
    preferred_alternatives: ['seated-good-morning', 'bird-dog'],
    rehab_for: ['low_back'],
    source: 'curated',
  },
  {
    id: 'jefferson-curl',
    name: 'Jefferson Curl',
    slug: 'jefferson-curl',
    aliases: ['jefferson curls', 'slant board jefferson curl', 'loaded spinal flexion'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'compound',
    level: 'expert',
    equipment: ['slant_board', 'dumbbell', 'plyo_box'],
    region_loads: { low_back: 0.8, spine: 0.9, posterior_chain: 0.7 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: true,
    plyo_contacts_per_rep: 0,
    kot_step: 'posterior_chain',
    cue: 'Chin to chest, roll down one vertebra at a time, wrists finish below the toes.',
    instructions: [
      'Stand on a raised platform or slant board holding a light dumbbell or kettlebell with straight arms.',
      'Tuck the chin and roll down one segment at a time, letting the spine flex deliberately.',
      'Keep the knees locked and the weight close to the legs.',
      'Descend until the wrists are below the toes, then roll back up segment by segment.',
      'Standard: 25% of bodyweight for 10 reps, wrists below the toes. LIGHT only, and only once pain-free (RESEARCH §6.3).',
    ],
    preferred_alternatives: ['elephant-walk', 'atg-rdl'],
    rehab_for: ['low_back', 'spine'],
    source: 'curated',
  },
  {
    id: 'atg-rdl',
    name: 'ATG RDL',
    slug: 'atg-rdl',
    aliases: ['atg romanian deadlift', 'knees over toes rdl', 'full range rdl'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['dumbbell', 'fixed_barbell', 'smith_machine'],
    region_loads: { posterior_chain: 1, hips_glutes: 0.7, low_back: 0.5 },
    load_style: 'total_dumbbell_pair',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    kot_step: 'posterior_chain',
    cue: 'Knees soft and locked in place, push the hips back, full hamstring stretch, flat back.',
    instructions: [
      'Stand tall holding dumbbells or a fixed bar at the hips, feet hip width.',
      'Push the hips straight back, keeping the shins near vertical and the back flat.',
      'Lower until you reach the end of the hamstring stretch — typically mid-shin — without rounding.',
      'Drive the hips forward to stand, squeezing the glutes at the top.',
      'Standard: 100% of bodyweight × 10, or 50% × 20. No floor deadlifts at Planet Fitness.',
    ],
    preferred_alternatives: ['seated-good-morning', 'nordic-hamstring-curl'],
    rehab_for: ['posterior_chain', 'low_back'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // McGill Big 3 (RESEARCH §6.3 — low-back rehab floor)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'mcgill-curl-up',
    name: 'McGill Curl-Up',
    slug: 'mcgill-curl-up',
    aliases: ['mcgill curl up', 'modified curl up', 'big 3 curl up'],
    pattern: 'anti_extension',
    force: 'static',
    mechanic: 'isolation',
    level: 'beginner',
    equipment: ['yoga_mat', 'bodyweight'],
    region_loads: { core: 0.8, spine: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Hands under the low back, one knee bent — lift the head and shoulders an inch, no more.',
    instructions: [
      'Lie on your back, one knee bent with the foot flat, the other leg straight.',
      'Slide both hands palm-down under the lumbar spine to preserve its natural arch.',
      'Brace the abdominals and lift the head, neck, and shoulders as one unit about an inch off the floor.',
      'Hold 10 seconds, breathing normally; do not flex the low back or push it into the floor.',
      'Use descending pyramids (6/4/2 reps) rather than long sets. Daily is fine.',
    ],
    preferred_alternatives: ['side-plank', 'bird-dog'],
    rehab_for: ['low_back', 'core'],
    source: 'curated',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    slug: 'side-plank',
    aliases: ['side bridge', 'mcgill side plank', 'big 3 side plank'],
    pattern: 'anti_lateral_flexion',
    force: 'static',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['yoga_mat', 'bodyweight'],
    region_loads: { core: 0.9, shoulders: 0.3, hips_glutes: 0.3, spine: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Straight line ear to ankle; push the floor away with the bottom elbow.',
    instructions: [
      'Lie on your side, elbow under the shoulder, knees bent (easier) or legs straight (harder).',
      'Lift the hips so the body forms a straight line from head to knees or ankles.',
      'Keep the top hip stacked over the bottom hip — no rolling forward.',
      'Hold 10 seconds per rep and repeat, rather than one long hold.',
      'Descending pyramids (6/4/2) each side. Daily is fine.',
    ],
    preferred_alternatives: ['mcgill-curl-up', 'bird-dog'],
    rehab_for: ['low_back', 'core'],
    source: 'curated',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    slug: 'bird-dog',
    aliases: ['birddog', 'quadruped opposite arm leg reach', 'big 3 bird dog'],
    pattern: 'anti_rotation',
    force: 'static',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['yoga_mat', 'bodyweight'],
    region_loads: { core: 0.7, low_back: 0.5, hips_glutes: 0.4, shoulders: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Reach long, not high — keep the hips level enough to balance a glass of water.',
    instructions: [
      'Start on hands and knees with a neutral spine, hands under shoulders, knees under hips.',
      'Brace the trunk and extend the opposite arm and leg until both are level with the torso.',
      'Do not arch the low back or let either hip rotate open.',
      'Hold 10 seconds, return, and sweep the hand and knee toward each other before the next rep.',
      'Descending pyramids (6/4/2) per side. Daily is fine.',
    ],
    preferred_alternatives: ['mcgill-curl-up', 'side-plank'],
    rehab_for: ['low_back', 'core'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Plyometrics & sprint ladder (RESEARCH §6.5)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'pogo-hop',
    name: 'Pogo Hop',
    slug: 'pogo-hop',
    aliases: ['pogo jumps', 'pogos', 'stiff ankle hops'],
    pattern: 'jump',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['bodyweight'],
    region_loads: { calves_achilles: 1, knees_quads: 0.3 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 1,
    cue: 'Stiff ankles, minimal knee bend, off the ground as fast as you touch it.',
    instructions: [
      'Stand tall with feet hip width, arms relaxed at the sides or on the hips.',
      'Bounce continuously off the balls of the feet, keeping the knees nearly straight.',
      'Minimize ground contact time — think "hot floor".',
      'Sets of 15–30 contacts. This is the entry rung of the plyometric ladder.',
      'Never on consecutive days; count contacts toward the weekly plyo budget.',
    ],
    preferred_alternatives: ['ankle-hop'],
    source: 'curated',
  },
  {
    id: 'ankle-hop',
    name: 'Ankle Hop',
    slug: 'ankle-hop',
    aliases: ['ankle hops', 'ankle bounces', 'low amplitude hops'],
    pattern: 'jump',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['bodyweight'],
    region_loads: { calves_achilles: 0.9, knees_quads: 0.2 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 1,
    cue: 'Small, quiet, rhythmic — the ankle does the work.',
    instructions: [
      'Stand tall, weight on the balls of the feet.',
      'Hop 2–4 inches off the ground using ankle action only.',
      'Land quietly through the forefoot with the knees soft but nearly straight.',
      'Sets of 20–30 contacts, resting fully between sets.',
      'Progress to pogo hops, then box jumps, before any depth work.',
    ],
    preferred_alternatives: ['pogo-hop'],
    source: 'curated',
  },
  {
    id: 'box-jump-step-down',
    name: 'Box Jump (Step Down)',
    slug: 'box-jump-step-down',
    aliases: ['box jump step down', 'box jump with step down', 'boxjump'],
    pattern: 'jump',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['plyo_box'],
    region_loads: { knees_quads: 0.8, hips_glutes: 0.7, calves_achilles: 0.5, posterior_chain: 0.4 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 1,
    cue: 'Jump up, land soft and tall, then STEP down — never jump down.',
    instructions: [
      'Set a box you can land on with the hips above parallel — height is not the goal.',
      'Dip, swing the arms, and jump onto the box.',
      'Land quietly with the whole foot on the box, knees tracking over the toes.',
      'Stand up fully, then step down one foot at a time.',
      'Sets of 3–5 reps, full recovery. Stepping down keeps the eccentric cost low.',
    ],
    preferred_alternatives: ['broad-jump', 'pogo-hop'],
    source: 'curated',
  },
  {
    id: 'hurdle-hop',
    name: 'Hurdle Hop',
    slug: 'hurdle-hop',
    aliases: ['hurdle hops', 'mini hurdle hops', 'cone hops'],
    pattern: 'jump',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['plyo_box', 'track_or_open_space'],
    region_loads: { calves_achilles: 0.8, knees_quads: 0.7, hips_glutes: 0.5 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 1,
    cue: 'Cycle the feet up and over, land and leave — short contacts.',
    instructions: [
      'Set 4–6 low hurdles or cones about 2–3 feet apart.',
      'Hop over them with both feet, keeping ground contact short.',
      'Land on the balls of the feet with the knees soft, absorbing through the hips.',
      'One pass = one set; count each landing as a contact.',
      'Stop the set the moment contacts get noisy or slow.',
    ],
    preferred_alternatives: ['pogo-hop', 'box-jump-step-down'],
    source: 'curated',
  },
  {
    id: 'broad-jump',
    name: 'Broad Jump',
    slug: 'broad-jump',
    aliases: ['standing long jump', 'standing broad jump'],
    pattern: 'jump',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['track_or_open_space'],
    region_loads: { hips_glutes: 0.9, knees_quads: 0.8, posterior_chain: 0.7, calves_achilles: 0.5 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 1,
    cue: 'Big arm swing, jump out not up, stick the landing.',
    instructions: [
      'Stand with feet hip width behind a line, on grass or a forgiving surface.',
      'Swing the arms back, dip the hips, and jump forward as far as you can.',
      'Land on both feet with the hips back and the knees tracking over the toes; stick it without a stumble.',
      'Sets of 3–5 reps with full recovery — this is a power test as well as training.',
      'Also used as a monthly athleticism benchmark alongside vertical jump.',
    ],
    preferred_alternatives: ['box-jump-step-down'],
    source: 'curated',
  },
  {
    id: 'depth-jump',
    name: 'Depth Jump',
    slug: 'depth-jump',
    aliases: ['drop jump', 'depth jumps'],
    pattern: 'jump',
    force: 'push',
    mechanic: 'compound',
    level: 'expert',
    equipment: ['plyo_box'],
    region_loads: { knees_quads: 1, calves_achilles: 0.8, posterior_chain: 0.7, hips_glutes: 0.7 },
    load_style: 'bodyweight',
    barbell_free: true,
    eccentric_dominant: true,
    plyo_contacts_per_rep: 2,
    cue: 'Step off, touch and go — off the floor faster than you landed.',
    instructions: [
      'Use a 12–18 inch box to start. Step off (do not jump off).',
      'Land on both forefeet and immediately rebound as high as possible.',
      'Ground contact should be brief and quiet; if you sink, the box is too tall.',
      'Sets of 3–5 reps, full recovery, never on consecutive days.',
      'GATED: only after landing mechanics and single-leg control are demonstrated, and never in the same session as Nordics (RESEARCH §6.3).',
    ],
    preferred_alternatives: ['box-jump-step-down', 'hurdle-hop'],
    contraindicated_with: ['nordic-hamstring-curl'],
    source: 'curated',
  },
  {
    id: 'acceleration-sprint',
    name: 'Acceleration Sprint (10–30 m)',
    slug: 'acceleration-sprint',
    aliases: ['sprint acceleration', '10m sprint', '30m sprint', 'short sprint'],
    pattern: 'sprint',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['track_or_open_space', 'outdoor_route'],
    region_loads: { posterior_chain: 0.9, hips_glutes: 0.8, knees_quads: 0.7, calves_achilles: 0.6 },
    load_style: 'none',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Push the ground back, rise gradually — do not pop upright in the first steps.',
    instructions: [
      'Warm up thoroughly: 5–10 minutes easy, then drills and 3–4 build-ups at rising effort.',
      'Sprint 10–30 m from a standing start, accelerating smoothly to top effort.',
      'Walk back and rest fully — roughly one minute per 10 m sprinted.',
      '6–10 reps total. Quality only: stop when times or feel drop off.',
      'Never the day after heavy lower-body eccentric work (RESEARCH §6.5).',
    ],
    preferred_alternatives: ['broad-jump'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Barbell-free conditioning (RESEARCH §2 — "CrossFit at Planet Fitness")
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'db-thruster',
    name: 'Dumbbell Thruster',
    slug: 'db-thruster',
    aliases: ['dumbbell thrusters', 'db thrusters', 'thruster'],
    pattern: 'vertical_push',
    force: 'push',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['dumbbell'],
    region_loads: { knees_quads: 0.7, shoulders: 0.8, hips_glutes: 0.5, core: 0.4, elbows_forearms: 0.3 },
    load_style: 'total_dumbbell_pair',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'One movement: squat, then drive the dumbbells overhead off the leg drive.',
    instructions: [
      'Hold dumbbells at the shoulders, elbows in front, feet shoulder width.',
      'Squat to at least parallel with the torso upright.',
      'Drive out of the bottom and use that momentum to press the dumbbells to lockout overhead.',
      'Lower to the shoulders and go straight into the next rep.',
      'The barbell-free metcon staple at Planet Fitness.',
    ],
    preferred_alternatives: ['db-push-press'],
    source: 'curated',
  },
  {
    id: 'db-snatch',
    name: 'Dumbbell Snatch',
    slug: 'db-snatch',
    aliases: ['single arm dumbbell snatch', 'db snatch', 'one arm snatch'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['dumbbell'],
    region_loads: { posterior_chain: 0.8, hips_glutes: 0.8, shoulders: 0.7, upper_back: 0.5, core: 0.4 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Hips snap, elbow high, punch under and lock out overhead in one motion.',
    instructions: [
      'Set a dumbbell between the feet, hinge with a flat back and grip it with one hand.',
      'Drive through the legs and snap the hips, keeping the dumbbell close to the body.',
      'Pull high and punch the hand through to lock out overhead with the bicep by the ear.',
      'Lower under control to the hang or to the floor and repeat; alternate arms per set.',
      'Load stays modest — this is a power movement, not a grind.',
    ],
    preferred_alternatives: ['db-clean', 'db-swing'],
    source: 'curated',
  },
  {
    id: 'db-clean',
    name: 'Dumbbell Clean',
    slug: 'db-clean',
    aliases: ['db cleans', 'dumbbell power clean', 'double db clean'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['dumbbell'],
    region_loads: { posterior_chain: 0.8, hips_glutes: 0.8, upper_back: 0.5, shoulders: 0.4, elbows_forearms: 0.3 },
    load_style: 'total_dumbbell_pair',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Hinge, snap, and meet the dumbbells at the shoulders — do not curl them.',
    instructions: [
      'Start with dumbbells beside the feet or at the hang, flat back, chest up.',
      'Extend the hips and knees explosively, shrugging as the dumbbells rise.',
      'Drop under and catch them at the shoulders in a quarter squat.',
      'Stand tall, then lower under control to the hang.',
      'Pairs with thrusters and push presses for barbell-free conditioning.',
    ],
    preferred_alternatives: ['db-snatch', 'db-swing'],
    source: 'curated',
  },
  {
    id: 'db-swing',
    name: 'Dumbbell Swing',
    slug: 'db-swing',
    aliases: ['dumbbell kettlebell swing', 'db swings', 'russian swing with dumbbell'],
    pattern: 'hinge',
    force: 'pull',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['dumbbell', 'kettlebell'],
    region_loads: { posterior_chain: 0.9, hips_glutes: 0.9, low_back: 0.4, core: 0.4 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Hips drive, arms are ropes — snap to a plank at the top, do not squat it.',
    instructions: [
      'Hold one dumbbell vertically by the head with both hands, feet slightly wider than hips.',
      'Hinge, hiking the dumbbell back between the legs with the back flat.',
      'Snap the hips forward to float the dumbbell to chest height; glutes and abs braced at the top.',
      'Let it fall back into the next hinge; keep a rhythm.',
      'Kettlebell if the gym has one; the DB version is the Planet Fitness substitute.',
    ],
    preferred_alternatives: ['db-clean', 'atg-rdl'],
    source: 'curated',
  },
  {
    id: 'db-push-press',
    name: 'Dumbbell Push Press',
    slug: 'db-push-press',
    aliases: ['db push press', 'dumbbell push presses'],
    pattern: 'vertical_push',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['dumbbell'],
    region_loads: { shoulders: 1, elbows_forearms: 0.4, core: 0.4, knees_quads: 0.3 },
    load_style: 'total_dumbbell_pair',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Short dip, hard drive, lock out with the biceps by the ears.',
    instructions: [
      'Hold dumbbells at the shoulders, feet hip width, ribs down.',
      'Dip 4–6 inches by bending the knees with the torso vertical.',
      'Drive up explosively and press the dumbbells to lockout overhead.',
      'Lower to the shoulders under control.',
      'Substitute for wall balls and barbell push presses at Planet Fitness.',
    ],
    preferred_alternatives: ['db-thruster'],
    source: 'curated',
  },
  {
    id: 'med-ball-slam',
    name: 'Medicine Ball Slam',
    slug: 'med-ball-slam',
    aliases: ['ball slam', 'slam ball', 'medicine ball slams'],
    pattern: 'rotation',
    force: 'push',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['slam_ball', 'medicine_ball'],
    region_loads: { core: 0.8, upper_back: 0.5, shoulders: 0.5, hips_glutes: 0.4 },
    load_style: 'single_implement',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Reach tall, then throw it through the floor — exhale on the slam.',
    instructions: [
      'Stand with feet hip width holding a slam ball (non-bouncing) at the chest.',
      'Reach the ball overhead, extending tall through the hips.',
      'Slam it into the floor between the feet, hinging and folding the torso as you throw.',
      'Pick it up and repeat, keeping the back flat as you reload.',
      'Check the club rules — some Planet Fitness locations disallow slams; substitute DB push press if so.',
    ],
    preferred_alternatives: ['db-push-press'],
    source: 'curated',
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Cardio pseudo-exercises — the engine prescribes these as whole sessions
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: 'zone-2-steady',
    name: 'Zone 2 Steady Cardio',
    slug: 'zone-2-steady',
    aliases: ['zone 2', 'z2', 'easy aerobic', 'conversational pace'],
    pattern: 'cardio_steady',
    force: 'unknown',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['stationary_bike', 'rower', 'treadmill', 'elliptical', 'outdoor_route'],
    region_loads: { calves_achilles: 0.2, knees_quads: 0.2, posterior_chain: 0.1 },
    load_style: 'none',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Nose-breathing, full-sentence pace. If you cannot talk, slow down.',
    instructions: [
      'Pick a modality: bike, rower, brisk walk, ruck, or easy run.',
      'Hold 60–70% of HRmax — conversational, sustainable, boring on purpose.',
      'Target 30–60 minutes; weekly target builds toward 180–240 minutes across 3–5 sessions.',
      'Use the bike or rower within 24 h of heavy lower-body work; save running for upper-body or recovery days.',
      'Ramp total weekly aerobic volume by no more than 10% per week.',
    ],
    preferred_alternatives: ['walk-run-progression'],
    source: 'curated',
  },
  {
    id: 'vo2-4x4-intervals',
    name: 'VO2max 4×4 Intervals',
    slug: 'vo2-4x4-intervals',
    aliases: ['4x4', 'norwegian 4x4', 'vo2 max intervals', 'four by four'],
    pattern: 'cardio_interval',
    force: 'unknown',
    mechanic: 'compound',
    level: 'intermediate',
    equipment: ['treadmill', 'stationary_bike', 'rower', 'outdoor_route'],
    region_loads: { calves_achilles: 0.3, knees_quads: 0.3, posterior_chain: 0.2 },
    load_style: 'none',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Four minutes hard enough that talking is impossible; three minutes easy. Four times.',
    instructions: [
      'Warm up 10 minutes easy, building to moderate.',
      'Work 4 minutes at 85–95% of HRmax — hard, controlled, sustainable for the full four.',
      'Recover 3 minutes at an easy pace, moving the whole time.',
      'Repeat for 4 total work intervals, then cool down 5–10 minutes.',
      'Once per week. Alternatives: 8×2 min or 30/30s if 4×4 is too much today.',
    ],
    preferred_alternatives: ['zone-2-steady'],
    source: 'curated',
  },
  {
    id: 'walk-run-progression',
    name: 'Walk–Run Progression',
    slug: 'walk-run-progression',
    aliases: ['walk run', 'run walk intervals', 'couch to 5k style'],
    pattern: 'cardio_steady',
    force: 'unknown',
    mechanic: 'compound',
    level: 'beginner',
    equipment: ['outdoor_route', 'treadmill'],
    region_loads: { calves_achilles: 0.4, knees_quads: 0.3, posterior_chain: 0.2 },
    load_style: 'none',
    barbell_free: true,
    eccentric_dominant: false,
    plyo_contacts_per_rep: 0,
    cue: 'Run the easy parts easy. The walk is part of the workout, not a failure.',
    instructions: [
      'Warm up 5 minutes walking briskly.',
      'Alternate run and walk intervals — e.g. 1 minute run / 2 minutes walk — for 20–30 minutes.',
      'Keep the run segments at conversational effort; the walk restores it.',
      'Add ~10% to total weekly running volume at most, and lengthen run segments before shortening walks.',
      'Never two hard run days back to back.',
    ],
    preferred_alternatives: ['zone-2-steady'],
    source: 'curated',
  },
];

/** Sorted by id so the emitted JSON is byte-stable. */
export const CURATED_EXERCISES: Exercise[] = [...CURATED].sort((a, b) => a.id.localeCompare(b.id));

/** The KOT movements RESEARCH §7 says the public datasets will miss. */
export const KOT_MOVEMENT_SLUGS: string[] = [
  'tibialis-raise',
  'patrick-step',
  'poliquin-step',
  'atg-split-squat',
  'backward-sled-drag',
  'reverse-nordic',
  'ql-extension',
  'seated-good-morning',
  'elephant-walk',
  'couch-stretch',
  'jefferson-curl',
  'atg-rdl',
];

function main(): void {
  const ids = CURATED_EXERCISES.map((e) => e.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length) throw new Error(`Duplicate curated exercise ids: ${dupes.join(', ')}`);
  writeJson(PATHS.curatedExercises, CURATED_EXERCISES);
  process.stdout.write(
    `Curated exercises — wrote ${CURATED_EXERCISES.length} records to ${PATHS.curatedExercises}\n`,
  );
}

if (process.argv[1] && /curated-exercises\.ts$/.test(process.argv[1])) main();
